services:
  - type: web
    name: apicoin
    env: python
    region: singapore
    plan: 7$
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python apicoin.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright
      - key: HOME
        value: /tmp
