services:
  - type: web
    name: apicoin
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: gunicorn apicoin:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright
      - key: HOME
        value: /tmp
