services:
  - type: web
    name: apitygia
    env: python
    region: singapore
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python apitygia.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /tmp/playwright

